### PR TITLE
Added setAxisRemap and setAxisSign functions

### PR DESCRIPTION
**Pull request by mrkaroshi**
Added these two functions to allow remapping of the axis and reversal of their direction also. The developer can then use the macros already provided in the original header.

### CODE REVIEW

**Comment by mrkaroshi** [comment]
Argh just realised this was already implemented!

**Comment by ronzeiller** [comment]
Axis and sign remapping is implemented, but how to call it as `write8` is private?

**Comment by mrkaroshi** [comment]
@ronzeiller are you having a problem with a specific function? Can you give a code snippet or example?

**Comment by ronzeiller** [comment]
@mrkaroshi 
Thank You for answering.
You wrote:

> Added these two functions to allow remapping of the axis and reversal of their direction also. The developer can then use the macros already provided in the original header.


This is perfect and exactly what I was looking for:
`void Adafruit_BNO055::setAxisRemap( adafruit_bno055_axis_remap_config_t remapcode )`

> Argh just realised this was already implemented!

but I cannot find these functions in the official library. And nothing similar?


And, btw do you know if other axis remapping e.g. for upright use of the sensor are also ok?

**Comment by mrkaroshi** [comment]
@ronzeiller if by 'upright' you mean remapping, say X to Z and Z to X, then the [datasheet](https://ae-bst.resource.bosch.com/media/_tech/media/datasheets/BST_BNO055_DS000_14.pdf) (on page 25) implies you can only have the sensor face down or face up.

Technically, if you imagine rotating the sensor around the X axis, you could just read the data from the Y axis into your Z variable, then invert the Z axis values before putting them into your Y variable.

If you do something like that, however, remember to apply offsets to your accelerometer accordingly (page 31) so that gravity is removed from Y instead of Z (for my specific example).

Does that answer your question ok?

**Comment by ronzeiller** [comment]
@mrkaroshi

> @ronzeiller if by 'upright' you mean remapping, say X to Z and Z to X, then the datasheet (on page 25) implies you can only have the sensor face down or face up.

Agree with this

> Technically, if you imagine rotating the sensor around the X axis, you could just read the data from the Y axis into your Z variable, then invert the Z axis values before putting them into your Y variable.

OK, this is clear so far

> If you do something like that, however, remember to apply offsets to your accelerometer accordingly (page 31) so that gravity is removed from Y instead of Z (for my specific example).

This I do not understand. I thought the offsets are done automatically by the sensor fusion.

Thank You for your effort, but even in the Bosch default's position this sensor does not work for me. Wanted to use it as compass for boating, but the heading is inferior and even when laying somewhere without any movement you can watch the value turning.....

**Comment by mrkaroshi** [comment]
@ronzeiller which axis drifts? Is the sensor near any sources of interference? Have you tried putting the BNO into Compass mode? I know magnetometers are mainly used for heading, depending on the sensor fusion balance, but they can be influenced by electromagnetic fields etc

That last part is about compensating the accelerometer to account for an orientation the BNO isn’t really designed for, even though it has a pretty robust fusion algorithm it’s still getting data from three sensors simultaneously - if one of them is accumulating noise, or worse drifting, your final orientation value will shift over time also. Page 43 of the datasheet explains a calibration procedure you can go through to get the best from the individual sensors, but also a register you can check to make sure the device has finished calibrating before you start using it's data.

[This video](https://www.youtube.com/watch?v=MrEPsA34daY) shows a few examples of interference and their effect on a hobbyist-grade navigation system.

**Comment by ronzeiller** [comment]
@mrkaroshi
> which axis drifts? 
Mainly the heading (personally I am using the sensor in default mounting position).
One thing is drift over time.
The other thing is that north is most of the time not north, compared to a magnetic compass, even if sensor is `fully calibrated`.
After each power on and careful calibration it shows slightly in another direction.

> Is the sensor near any sources of interference? 
No, today I even took it out of the case with Teensy and WiFi and put it into a separate box (plastic, no screws, nothing)

> Have you tried putting the BNO into Compass mode?
No, because we need tilt compensation, roll and pitch too.

Now the sensor was laying without any movement, fully calibrated, without any changes of things nearby. 
After 5 hours it was showing a drift of 2 degrees, full calibration, at constant room temperature.
When I moved the sensor a little bit it, suddenly it lost fully calibrated status (sysCal went to 0, magCal still on 3, accCal went to 1)

Any ideas what is wrong with it?

**Pull request merged**
