### PR TITLE
added documentation on Arduino Zero compatibility

### PR DESCRIPTION
**Pull request by dhiltonp**
Fixes issue #13.

### CODE REVIEW

**Comment by ladyada** [comment]
huh why would that be? is this just experimentally determined?

**Comment by dhiltonp** [comment]
http://forums.adafruit.com/viewtopic.php?f=19&t=88879

Running an i2c bus scan without anything connected, a mysterious device shows up at 0x28.

Basically, the debug chip on the Zero is (mistakenly?) connected to the MCU's i2c bus. It's shown in the Zero's schematic, but I think it's a mistake because the EDBG chip's i2c is intended to talk to the PC, not the MCU. It also has this undesirable side effect.

**Comment by ladyada** [comment]
oooOooooHhhh
that explains a lot

**Comment by ladyada** [comment]
sweet :)

**Comment by vuthuhuong** [comment]
Hello guys
I am getting a problem with feather M0 connected with BNO055
I posted here
 https://forums.adafruit.com/viewtopic.php?f=8&t=110686
If you have any experience please show me how I resolve it? thanks

**Pull request merged**
