### PR TITLE
Added default I2C address

### PR DESCRIPTION
**Pull request by Combinacijus**
It took a long time to understand that I need to pass address to Adafruit_BNO055().
By adding default address (0x29) it should work on first run and save someone a headache. 
Also changed Serial baud rate to 115200 for continuity between examples.

### CODE REVIEW

**Comment by ladyada** [comment]
please make back compatible with existing examples

**Comment by Combinacijus** [comment]
> default address is 0x28
> 
> https://github.com/adafruit/Adafruit_BNO055/blob/master/Adafruit_BNO055.h#L283

Oh ok didn't see that. But default address of my sensor was 0x29 so it didn't work for me and there was no comment that I should initialize with different address.
So should I change it to 0x28 or else?

**Comment by ladyada** [comment]
you can add a comment or set it to 0x28. what you can't do is break the code for every other person!

**Comment by Combinacijus** [comment]
> you can add a comment or set it to 0x28. what you can't do is break the code for every other person!

Ok thanks for your insight

**Comment by hoffmannjan** [comment]
works for me first time without your changes, only problem is baud settings that can be unified

**Comment by Combinacijus** [comment]
@hoffmannjan but for some people it might not work without changes and it's quite difficult to understand the problem for I2C beginners.
And because as you said it works for you I haven't changed default address so it won't break code. I have just added passing address to the initializer call and comment above that explains that you might need to change it.

**Comment by ladyada** [comment]
@hoffmannjan does this code still work with the added i2c addresses?

**Comment by hoffmannjan** [comment]
> @hoffmannjan does this code still work with the added i2c addresses?

yeap

**Pull request merged**
